/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nrkprosjekt;

import java.awt.Font;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Simen
 */
public class MetaEdit extends javax.swing.JDialog {

    Font font;
    JLabel progress = new JLabel();
    JLabel progresse = new JLabel();
    JLabel suc = new JLabel();
    JLabel textInfo = new JLabel("Saving...");
    Thread thread;
    int simluationSpeed = 1000;
    int counter = 0;
    HashMap<String, JTextField> tags;

    /**
     * Creates new form metaEdit
     */
    public MetaEdit(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        tags = new HashMap<>();
        initComponents();
        initProgressBar();
        addMouseListeners();
        loadMetaEditDialog();
        font = new java.awt.Font("Calibri Light", 0, 24);
        loadFont();
        fillMap();


    }

    public void fill(JTextField text, String name) {
        text.setName(name);
        tags.put(name, text);
    }

    public void fillMap() {
        fill(INAM, "INAM");
        fill(IART, "IART");
        fill(IGNR, "IGNR");
        fill(IKEY, "IKEY");
        fill(ISRF, "ISRF");
        fill(IMED, "IMED");
        fill(IENG, "IENG");
        fill(ITCH, "ITCH");
        fill(ISRC, "ISRC");
        fill(ICOP, "ICOP");
        fill(ISFT, "ISFT");
        fill(ICRD, "ICRD");
        fill(IALB, "IALB");
        fill(ILAN, "ILAN");
        
        
        fill(ICMT, "ICMT");
        fill(ISBJ, "ISBJ");

    }

    public void addMouseListeners() {
        mouseTextField(INAM);
        mouseTextField(IART);
        mouseTextField(IGNR);
        mouseTextField(IKEY);
        mouseTextField(ISRF);
        mouseTextField(IMED);
        mouseTextField(IENG);
        mouseTextField(ITCH);
        mouseTextField(ISRC);
        mouseTextField(ICOP);
        mouseTextField(ISFT);
        mouseTextField(ICRD);
        mouseTextField(IALB);
        mouseTextField(ILAN);
        mouseTextField(ICMT);
        mouseTextField(ISBJ);
    }

    public void setText(String tag, String data) {
        if (tags.containsKey(tag)) {

            if (data.contains("finnes ikke")) {
                //nothing
            } else {
                tags.get(tag).setText(data);
                tags.get(tag).setForeground(new java.awt.Color(44, 47, 54));
                tags.get(tag).setBackground(new java.awt.Color(232, 255, 232));
            }

        }
    }

    public void loadFont() {
        jLabel1.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        subTitle.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel1.getGraphics();
        jLabel1.getGraphics().getFontMetrics(font);
    }

    public void loadMetaEditDialog() {
        setResizable(false);
        setSize(500, 600);
        setLocationRelativeTo(null);
    }

    public void initProgressBar() {

        textInfo.setBounds(30, 550, 70, 10);
        textInfo.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        jPanel1.add(textInfo);
        textInfo.setVisible(false);


        suc.setBounds(400, 545, 20, 20);
        suc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/sucess3.png")));
        jPanel1.add(suc);
        suc.setVisible(false);

        progress.setBounds(95, 550, 0, 10);
        progress.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/prosessedBar.png")));
        jPanel1.add(progress);

        progresse.setBounds(95, 550, 300, 10);
        progresse.setText("f");
        progresse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/prosessed.png")));
        jPanel1.add(progresse);




    }

    public void setTextTitles(String text, String subText) {
        jLabel1.setText("Metadata for " + text);
        subTitle.setText("By " + subText);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        IART = new javax.swing.JTextField();
        ILAN = new javax.swing.JTextField();
        INAM = new javax.swing.JTextField();
        IGNR = new javax.swing.JTextField();
        IKEY = new javax.swing.JTextField();
        ISRF = new javax.swing.JTextField();
        IMED = new javax.swing.JTextField();
        IENG = new javax.swing.JTextField();
        ITCH = new javax.swing.JTextField();
        ISRC = new javax.swing.JTextField();
        ICOP = new javax.swing.JTextField();
        ISFT = new javax.swing.JTextField();
        ICRD = new javax.swing.JTextField();
        IALB = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ICMT = new javax.swing.JTextField();
        ISBJ = new javax.swing.JTextField();
        subTitle = new javax.swing.JLabel();
        checkCopy = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 600));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(44, 47, 54));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Metadata for Mabvuto");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 480, 40);

        IART.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        IART.setForeground(new java.awt.Color(153, 153, 153));
        IART.setText("Artist");
        IART.setToolTipText("Artist");
        IART.setPreferredSize(new java.awt.Dimension(170, 35));
        jPanel1.add(IART);
        IART.setBounds(260, 70, 170, 35);

        ILAN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ILAN.setForeground(new java.awt.Color(153, 153, 153));
        ILAN.setText("Language");
        ILAN.setToolTipText("Language");
        ILAN.setPreferredSize(new java.awt.Dimension(170, 35));
        jPanel1.add(ILAN);
        ILAN.setBounds(260, 420, 170, 35);

        INAM.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        INAM.setForeground(new java.awt.Color(153, 153, 153));
        INAM.setText("Track");
        INAM.setToolTipText("Track");
        INAM.setPreferredSize(new java.awt.Dimension(170, 35));
        INAM.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                INAMFocusGained(evt);
            }
        });
        jPanel1.add(INAM);
        INAM.setBounds(70, 70, 170, 35);

        IGNR.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        IGNR.setForeground(new java.awt.Color(153, 153, 153));
        IGNR.setText("Genre");
        IGNR.setToolTipText("Genre");
        IGNR.setPreferredSize(new java.awt.Dimension(170, 35));
        jPanel1.add(IGNR);
        IGNR.setBounds(70, 120, 170, 35);

        IKEY.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        IKEY.setForeground(new java.awt.Color(153, 153, 153));
        IKEY.setText("Keywords");
        IKEY.setToolTipText("Keywords");
        IKEY.setPreferredSize(new java.awt.Dimension(170, 35));
        jPanel1.add(IKEY);
        IKEY.setBounds(260, 120, 170, 35);

        ISRF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ISRF.setForeground(new java.awt.Color(153, 153, 153));
        ISRF.setText("Digitization Source");
        ISRF.setToolTipText("Digitization Source");
        ISRF.setPreferredSize(new java.awt.Dimension(170, 35));
        jPanel1.add(ISRF);
        ISRF.setBounds(70, 170, 170, 35);

        IMED.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        IMED.setForeground(new java.awt.Color(153, 153, 153));
        IMED.setText("Original Medium");
        IMED.setToolTipText("Original Medium");
        IMED.setPreferredSize(new java.awt.Dimension(170, 35));
        jPanel1.add(IMED);
        IMED.setBounds(260, 170, 170, 35);

        IENG.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        IENG.setForeground(new java.awt.Color(153, 153, 153));
        IENG.setText("Engineers");
        IENG.setToolTipText("Engineers");
        IENG.setPreferredSize(new java.awt.Dimension(170, 35));
        jPanel1.add(IENG);
        IENG.setBounds(70, 220, 170, 35);

        ITCH.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ITCH.setForeground(new java.awt.Color(153, 153, 153));
        ITCH.setText("Digitizer");
        ITCH.setToolTipText("Digitizer");
        ITCH.setPreferredSize(new java.awt.Dimension(170, 35));
        jPanel1.add(ITCH);
        ITCH.setBounds(260, 220, 170, 35);

        ISRC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ISRC.setForeground(new java.awt.Color(153, 153, 153));
        ISRC.setText("Source Supplier");
        ISRC.setToolTipText("Source Supplier");
        ISRC.setPreferredSize(new java.awt.Dimension(170, 35));
        jPanel1.add(ISRC);
        ISRC.setBounds(70, 270, 170, 35);

        ICOP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ICOP.setForeground(new java.awt.Color(153, 153, 153));
        ICOP.setText("Copyright");
        ICOP.setToolTipText("Copyright");
        ICOP.setPreferredSize(new java.awt.Dimension(170, 35));
        jPanel1.add(ICOP);
        ICOP.setBounds(260, 270, 170, 35);

        ISFT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ISFT.setForeground(new java.awt.Color(153, 153, 153));
        ISFT.setText("Software Package");
        ISFT.setToolTipText("Software Package");
        ISFT.setPreferredSize(new java.awt.Dimension(170, 35));
        jPanel1.add(ISFT);
        ISFT.setBounds(70, 320, 170, 35);

        ICRD.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ICRD.setForeground(new java.awt.Color(153, 153, 153));
        ICRD.setText("Creation Date");
        ICRD.setToolTipText("Creation Date");
        ICRD.setPreferredSize(new java.awt.Dimension(170, 35));
        jPanel1.add(ICRD);
        ICRD.setBounds(260, 320, 170, 35);

        IALB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        IALB.setForeground(new java.awt.Color(153, 153, 153));
        IALB.setText("Album");
        IALB.setToolTipText("Album");
        IALB.setPreferredSize(new java.awt.Dimension(170, 35));
        jPanel1.add(IALB);
        IALB.setBounds(70, 420, 170, 35);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/buttonCancel.png"))); // NOI18N
        jButton1.setText("Cancel");
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setIconTextGap(-108);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/buttonCancelOver.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(260, 500, 170, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/buttonSave.png"))); // NOI18N
        jButton2.setText("Save");
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.setIconTextGap(-105);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/buttonSaveOver.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(70, 500, 170, 40);

        ICMT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ICMT.setForeground(new java.awt.Color(153, 153, 153));
        ICMT.setText("Comments");
        ICMT.setToolTipText("Comments");
        ICMT.setPreferredSize(new java.awt.Dimension(170, 35));
        jPanel1.add(ICMT);
        ICMT.setBounds(70, 370, 170, 35);

        ISBJ.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ISBJ.setForeground(new java.awt.Color(153, 153, 153));
        ISBJ.setText("Subjects");
        ISBJ.setToolTipText("Subjects");
        ISBJ.setPreferredSize(new java.awt.Dimension(170, 35));
        jPanel1.add(ISBJ);
        ISBJ.setBounds(260, 370, 170, 35);

        subTitle.setForeground(new java.awt.Color(66, 68, 72));
        subTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subTitle.setText("subTitle");
        subTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(subTitle);
        subTitle.setBounds(0, 44, 490, 20);

        checkCopy.setText("Create a copy on the harddrive");
        jPanel1.add(checkCopy);
        checkCopy.setBounds(70, 470, 180, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void INAMFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_INAMFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_INAMFocusGained

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       if(checkCopy.isSelected()){
       System.out.println("Skriver kopi...");
       } 
        thread = new Thread(new Runnable() {
            public void run() {

                textInfo.setVisible(true);
                while (progress.getSize().width < 300) {
                    if (counter == simluationSpeed) {
                        progress.setSize(progress.getSize().width + 1, 10);
                        simluationSpeed += 10000;
                        counter = 0;
                    }

                    counter++;
                }
                textInfo.setText("Saved");
                suc.setVisible(true);


            }
        });
        try {
            Thread.sleep(1000 / 30);
        } catch (InterruptedException ex) {
            Logger.getLogger(MetaEdit.class.getName()).log(Level.SEVERE, null, ex);
        }
        thread.start();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tekstClicked(java.awt.event.MouseEvent evt, JTextField text) {
        if (text.getText().equals(text.getToolTipText())) {
            text.setText("");
            text.setForeground(new java.awt.Color(44, 47, 54));

        }

    }

    private void textFocusLost(java.awt.event.FocusEvent evt, JTextField text) {
        if (text.getText().equals("")) {
            text.setBackground(new java.awt.Color(255, 255, 255));
            text.setForeground(new java.awt.Color(153, 153, 153));

            text.setText(text.getToolTipText());
        } else {
            text.setBackground(new java.awt.Color(232, 255, 232));
        }

    }

    private void textFocusGained(java.awt.event.FocusEvent evt, JTextField text) {
        if (text.getText().equals(text.getToolTipText())) {
            text.setText("");
            text.setForeground(new java.awt.Color(44, 47, 54));
        }

    }

    private void mouseTextField(final JTextField textField) {
        textField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tekstClicked(evt, textField);
            }
        });
        textField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFocusLost(evt, textField);
            }

            public void focusGained(java.awt.event.FocusEvent evt) {
                textFocusGained(evt, textField);
            }
        });

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MetaEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MetaEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MetaEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MetaEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MetaEdit dialog = new MetaEdit(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IALB;
    private javax.swing.JTextField IART;
    private javax.swing.JTextField ICMT;
    private javax.swing.JTextField ICOP;
    private javax.swing.JTextField ICRD;
    private javax.swing.JTextField IENG;
    private javax.swing.JTextField IGNR;
    private javax.swing.JTextField IKEY;
    private javax.swing.JTextField ILAN;
    private javax.swing.JTextField IMED;
    private javax.swing.JTextField INAM;
    private javax.swing.JTextField ISBJ;
    private javax.swing.JTextField ISFT;
    private javax.swing.JTextField ISRC;
    private javax.swing.JTextField ISRF;
    private javax.swing.JTextField ITCH;
    private javax.swing.JCheckBox checkCopy;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel subTitle;
    // End of variables declaration//GEN-END:variables
}
